version: "3.8"

services:
  invitations-service:
    build: .
    container_name: coffeetech-invitations-service
    ports:
      - "8003:8000"
    env_file: .env
    networks:
      - common
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  common:
    external: true
    name: coffeetech_network
